Fix exec_env_tls assertion in module instantiation
bytecodealliance/wasm-micro-runtime pull request #3844
Opened 2024-10-07 10:46 UTC by wenyongh

The execute_post_instantiate_functions may be triggered by wasm_cluster_spawn_exec_env,
in which the exec_env_tls can be NULL and cause the assertion invalid.

p.s. https://github.com/bytecodealliance/wasm-micro-runtime/issues/3839.

2024-10-07 10:58 UTC, lum1n0us requested changes
LGTM

2024-10-07 12:37 UTC, lum1n0us approved these changes
LGTM

2024-10-07 16:45 UTC, woodsmc commented
This appears to resolve the issue!

2024-10-08 01:50 UTC, xujuntwt95329 approved these changes

2024-10-08 02:08 UTC, merged